// Generated by gencpp from file arm_pkg/handle_info.msg
// DO NOT EDIT!


#ifndef ARM_PKG_MESSAGE_HANDLE_INFO_H
#define ARM_PKG_MESSAGE_HANDLE_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_pkg
{
template <class ContainerAllocator>
struct handle_info_
{
  typedef handle_info_<ContainerAllocator> Type;

  handle_info_()
    : left_x(0.0)
    , left_y(0.0)
    , right_x(0.0)
    , right_y(0.0)
    , left_putter_a(0)
    , right_putter_b(0)
    , left_button_vra(0.0)
    , right_button_vrb(0.0)
    , connected(0)  {
    }
  handle_info_(const ContainerAllocator& _alloc)
    : left_x(0.0)
    , left_y(0.0)
    , right_x(0.0)
    , right_y(0.0)
    , left_putter_a(0)
    , right_putter_b(0)
    , left_button_vra(0.0)
    , right_button_vrb(0.0)
    , connected(0)  {
  (void)_alloc;
    }



   typedef double _left_x_type;
  _left_x_type left_x;

   typedef double _left_y_type;
  _left_y_type left_y;

   typedef double _right_x_type;
  _right_x_type right_x;

   typedef double _right_y_type;
  _right_y_type right_y;

   typedef int8_t _left_putter_a_type;
  _left_putter_a_type left_putter_a;

   typedef int8_t _right_putter_b_type;
  _right_putter_b_type right_putter_b;

   typedef double _left_button_vra_type;
  _left_button_vra_type left_button_vra;

   typedef double _right_button_vrb_type;
  _right_button_vrb_type right_button_vrb;

   typedef int8_t _connected_type;
  _connected_type connected;





  typedef boost::shared_ptr< ::arm_pkg::handle_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_pkg::handle_info_<ContainerAllocator> const> ConstPtr;

}; // struct handle_info_

typedef ::arm_pkg::handle_info_<std::allocator<void> > handle_info;

typedef boost::shared_ptr< ::arm_pkg::handle_info > handle_infoPtr;
typedef boost::shared_ptr< ::arm_pkg::handle_info const> handle_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_pkg::handle_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_pkg::handle_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_pkg::handle_info_<ContainerAllocator1> & lhs, const ::arm_pkg::handle_info_<ContainerAllocator2> & rhs)
{
  return lhs.left_x == rhs.left_x &&
    lhs.left_y == rhs.left_y &&
    lhs.right_x == rhs.right_x &&
    lhs.right_y == rhs.right_y &&
    lhs.left_putter_a == rhs.left_putter_a &&
    lhs.right_putter_b == rhs.right_putter_b &&
    lhs.left_button_vra == rhs.left_button_vra &&
    lhs.right_button_vrb == rhs.right_button_vrb &&
    lhs.connected == rhs.connected;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_pkg::handle_info_<ContainerAllocator1> & lhs, const ::arm_pkg::handle_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_pkg::handle_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_pkg::handle_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_pkg::handle_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_pkg::handle_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_pkg::handle_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_pkg::handle_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_pkg::handle_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "508756f475519ffbaa213660eb366a74";
  }

  static const char* value(const ::arm_pkg::handle_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x508756f475519ffbULL;
  static const uint64_t static_value2 = 0xaa213660eb366a74ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_pkg::handle_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_pkg/handle_info";
  }

  static const char* value(const ::arm_pkg::handle_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_pkg::handle_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_x\n"
"float64 left_y\n"
"float64 right_x\n"
"float64 right_y\n"
"int8  left_putter_a\n"
"int8  right_putter_b\n"
"float64 left_button_vra\n"
"float64 right_button_vrb\n"
"int8 connected\n"
;
  }

  static const char* value(const ::arm_pkg::handle_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_pkg::handle_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_x);
      stream.next(m.left_y);
      stream.next(m.right_x);
      stream.next(m.right_y);
      stream.next(m.left_putter_a);
      stream.next(m.right_putter_b);
      stream.next(m.left_button_vra);
      stream.next(m.right_button_vrb);
      stream.next(m.connected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct handle_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_pkg::handle_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_pkg::handle_info_<ContainerAllocator>& v)
  {
    s << indent << "left_x: ";
    Printer<double>::stream(s, indent + "  ", v.left_x);
    s << indent << "left_y: ";
    Printer<double>::stream(s, indent + "  ", v.left_y);
    s << indent << "right_x: ";
    Printer<double>::stream(s, indent + "  ", v.right_x);
    s << indent << "right_y: ";
    Printer<double>::stream(s, indent + "  ", v.right_y);
    s << indent << "left_putter_a: ";
    Printer<int8_t>::stream(s, indent + "  ", v.left_putter_a);
    s << indent << "right_putter_b: ";
    Printer<int8_t>::stream(s, indent + "  ", v.right_putter_b);
    s << indent << "left_button_vra: ";
    Printer<double>::stream(s, indent + "  ", v.left_button_vra);
    s << indent << "right_button_vrb: ";
    Printer<double>::stream(s, indent + "  ", v.right_button_vrb);
    s << indent << "connected: ";
    Printer<int8_t>::stream(s, indent + "  ", v.connected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_PKG_MESSAGE_HANDLE_INFO_H
