# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from arm_pkg/handle_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class handle_info(genpy.Message):
  _md5sum = "508756f475519ffbaa213660eb366a74"
  _type = "arm_pkg/handle_info"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 left_x
float64 left_y
float64 right_x
float64 right_y
int8  left_putter_a
int8  right_putter_b
float64 left_button_vra
float64 right_button_vrb
int8 connected
"""
  __slots__ = ['left_x','left_y','right_x','right_y','left_putter_a','right_putter_b','left_button_vra','right_button_vrb','connected']
  _slot_types = ['float64','float64','float64','float64','int8','int8','float64','float64','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_x,left_y,right_x,right_y,left_putter_a,right_putter_b,left_button_vra,right_button_vrb,connected

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(handle_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.left_x is None:
        self.left_x = 0.
      if self.left_y is None:
        self.left_y = 0.
      if self.right_x is None:
        self.right_x = 0.
      if self.right_y is None:
        self.right_y = 0.
      if self.left_putter_a is None:
        self.left_putter_a = 0
      if self.right_putter_b is None:
        self.right_putter_b = 0
      if self.left_button_vra is None:
        self.left_button_vra = 0.
      if self.right_button_vrb is None:
        self.right_button_vrb = 0.
      if self.connected is None:
        self.connected = 0
    else:
      self.left_x = 0.
      self.left_y = 0.
      self.right_x = 0.
      self.right_y = 0.
      self.left_putter_a = 0
      self.right_putter_b = 0
      self.left_button_vra = 0.
      self.right_button_vrb = 0.
      self.connected = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d2b2db().pack(_x.left_x, _x.left_y, _x.right_x, _x.right_y, _x.left_putter_a, _x.right_putter_b, _x.left_button_vra, _x.right_button_vrb, _x.connected))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 51
      (_x.left_x, _x.left_y, _x.right_x, _x.right_y, _x.left_putter_a, _x.right_putter_b, _x.left_button_vra, _x.right_button_vrb, _x.connected,) = _get_struct_4d2b2db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d2b2db().pack(_x.left_x, _x.left_y, _x.right_x, _x.right_y, _x.left_putter_a, _x.right_putter_b, _x.left_button_vra, _x.right_button_vrb, _x.connected))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 51
      (_x.left_x, _x.left_y, _x.right_x, _x.right_y, _x.left_putter_a, _x.right_putter_b, _x.left_button_vra, _x.right_button_vrb, _x.connected,) = _get_struct_4d2b2db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d2b2db = None
def _get_struct_4d2b2db():
    global _struct_4d2b2db
    if _struct_4d2b2db is None:
        _struct_4d2b2db = struct.Struct("<4d2b2db")
    return _struct_4d2b2db
